data = [{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
         "question": "The retail disc of Tony Hawk&#039;s Pro Skater 5 only comes with the tutorial.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Mythology", "type": "boolean", "difficulty": "easy",
         "question": "According to Greek Mythology, Zeus can control lightning.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
         "question": "An atom contains a nucleus.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "You can legally drink alcohol while driving in Mississippi.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "The PlayStation was originally a joint project between Sega and Sony"
                     " that was a Sega Genesis with a disc drive.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "Pluto is a planet.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
         "question": "The Sonoran Desert is located in eastern Africa.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
         "question": "Liechtenstein does not have an airport.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "California is larger than Japan.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "medium",
         "question": "Oxford University is older than the Aztec Empire. ",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
         "question": "Zero factorial is equal to zero. ", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
         "question": "A &#039;Millinillion&#039; is a real number.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
         "question": "In &quot;Star Trek&quot;, Klingons are aliens.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Celebrities", "type": "boolean", "difficulty": "hard",
         "question": "Lady Gaga&#039;s real name is Stefani Joanne Angelina Germanotta.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
         "difficulty": "easy",
         "question": "Waylon Smithers from &quot;The Simpsons&quot; was originally black when he first appeared in the series.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "Pneumonoultramicroscopicsilicovolcanoconiosis is a synonym for the disease known as silicosis.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "Rabbits can see what&#039;s behind themselves without turning their heads.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
         "difficulty": "medium",
         "question": "Blue Danube was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
         "question": "In The Witcher 3, the Zoltan Chivay Gwent card can be found under the Hanged Man&#039;s Tree.",
         "correct_answer": "True", "incorrect_answers": ["False"]}]
